version: '3'

services:
  mysql:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest

  redis:
    image: redis:7.0.8-alpine 

  app: 
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
